[package]
name = "tunnelproxy-edge"
description = "TunnelProxy public ingress and live tunnel routing."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
tokio-rustls = { workspace = true }
tunnelproxy-protocol = { path = "../protocol" }
tunnelproxy-common = { path = "../common" }
tunnelproxy-control-plane = { path = "../control-plane" }
bytes = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
sha1 = { workspace = true }
base64 = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tunnelproxy-agent = { path = "../agent" }
rcgen = { workspace = true }
time = { workspace = true }
sha2 = { workspace = true }
